export const nav = {
  HOME: "/home",
  LOGIN: "/",
  ADMIN_HOME: "/admin_home",
  USERS: "/users",
  DSE: "/dse",
  LINES: "/lines",
  CREATE_LINE: "/create-line",
  CREATE_USER: "/create-user",
  CREATE_DSE: "/create-dse",
  SHOPS: "/shops",
  CREATE_SHOP: "/create-shop",
  MAPPINGS: "/mappings",
  CREATE_REPORT: "/create-report",
  REPORT_LIST: "/report-list",
  VIEW_REPORT: "/report-view",
  STOCK: "/stock",
  ADDSTOCK: "/add-stock",
  RESETPASSWORD: "/resetpassword",
  EDITDSE: "/editdsc",
};
